# Generated by Django 6.0.4 on 2026-04-14 09:46

from django.db import migrations, models


def copy_role_to_is_specialist(apps, schema_editor):
    """Set is_specialist=True for users who had role='SPECIALIST'."""
    User = apps.get_model('core', 'User')
    User.objects.filter(role='SPECIALIST').update(is_specialist=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        # 1. Add the new boolean field first (default=False)
        migrations.AddField(
            model_name='user',
            name='is_specialist',
            field=models.BooleanField(default=False),
        ),
        # 2. Copy data: role='SPECIALIST' → is_specialist=True
        migrations.RunPython(copy_role_to_is_specialist, migrations.RunPython.noop),
        # 3. Remove the old role field
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
