# Generated by Django 6.0.4 on 2026-04-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_role_user_is_specialist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialist',
            new_name='SpecialistDetails',
        ),
        migrations.AlterModelOptions(
            name='specialistdetails',
            options={'ordering': ['name'], 'verbose_name': 'Specialist Details', 'verbose_name_plural': 'Specialist Details'},
        ),
    ]
